export type Product = {
  slug: string
  name: string
  description: string
  image: string
  minOrderKg: number
  specifications: {
    polymer: string
    grade?: string
    mfi?: string // Melt Flow Index
    density?: string
    colorOptions?: string
    recycling?: string
  }
  applications: string[]
  packaging: string
  category: string
}

export const products: Product[] = [
  // -------------------- PP Granules --------------------
  {
    slug: "pp-homo-natural",
    name: "PP Homo Natural Granules",
    description: "High-rigidity polypropylene homopolymer granules with excellent processability.",
    image: "/hdpe-blowing-grade-natural-granule-500x500.webp",
    minOrderKg: 25,
    specifications: {
      polymer: "PP Homo",
      grade: "Injection",
      mfi: "10–20 g/10min (230°C/2.16kg)",
      density: "≈0.90 g/cm³",
      colorOptions: "Natural / White",
      recycling: "Virgin & recycled available",
    },
    applications: ["Household goods", "Electricals", "Caps", "Stationery"],
    packaging: "25 kg bags, palletized",
    category: "PP Granules",
  },
  {
    slug: "pp-copolymer-colored",
    name: "PP Copolymer Colored Granules",
    description: "Tough copolymer PP granules with color customization for impact resistance.",
    image: "/allpackates.jpg",
    minOrderKg: 25,
    specifications: {
      polymer: "PP Copolymer",
      grade: "Injection",
      mfi: "6–12 g/10min",
      density: "≈0.91 g/cm³",
      colorOptions: "Custom shades (RAL/Pantone)",
      recycling: "Available on request",
    },
    applications: ["Automotive trims", "Bins", "Crates", "Containers"],
    packaging: "25 kg bags",
    category: "PP Granules",
  },
  {
    slug: "pp-black-reprocessed",
    name: "PP Black Reprocessed Granules",
    description: "Cost-effective reprocessed PP granules with controlled properties.",
    image: "/black.jpg",
    minOrderKg: 25,
    specifications: {
      polymer: "Reprocessed PP",
      grade: "Injection/Extrusion",
      mfi: "Varies by batch",
      density: "≈0.90 g/cm³",
      colorOptions: "Black / mixed",
      recycling: "100% post-industrial waste",
    },
    applications: ["Non-critical components", "Utility bins", "Furniture", "Planters"],
    packaging: "25 kg bags",
    category: "PP Granules",
  },
  {
    slug: "pp-colored-masterbatch",
    name: "PP Colored Masterbatch Granules",
    description: "Custom shade-matched PP granules ensuring batch consistency.",
    image: "/product-jpeg-500x500.webp",
    minOrderKg: 25,
    specifications: {
      polymer: "PP (Homo/Copolymer)",
      grade: "Injection/Extrusion",
      mfi: "5–15 g/10min",
      density: "≈0.91 g/cm³",
      colorOptions: "Any RAL/Pantone",
      recycling: "Virgin and recycled options",
    },
    applications: ["Toys", "Appliances", "Containers", "Stationery"],
    packaging: "25 kg bags",
    category: "PP Granules",
  },
  {
    slug: "pp-virgin-high-flow",
    name: "PP Virgin High Flow Granules",
    description: "Virgin PP with high melt flow index for thin-walled applications.",
    image: "/natural-pp-blow-granules-500x500.webp",
    minOrderKg: 25,
    specifications: {
      polymer: "Virgin PP",
      grade: "Injection",
      mfi: "25–35 g/10min",
      density: "≈0.90 g/cm³",
      colorOptions: "Natural / custom",
      recycling: "Virgin only",
    },
    applications: ["Thin-wall containers", "Medical devices", "Packaging"],
    packaging: "25 kg bags",
    category: "PP Granules",
  },

  // -------------------- HDPE Granules --------------------
  {
    slug: "hdpe-blow-grade-natural",
    name: "HDPE Blow Grade Natural",
    description: "Natural HDPE granules suitable for blow molding bottles and containers.",
    image: "/hdpe-blowing-grade-natural-granule-500x500 (1).webp",
    minOrderKg: 25,
    specifications: {
      polymer: "HDPE",
      grade: "Blow",
      mfi: "0.3–0.8 g/10min",
      density: "0.955 g/cm³",
      colorOptions: "Natural",
      recycling: "Virgin",
    },
    applications: ["Milk bottles", "Canisters", "Drums", "Tanks"],
    packaging: "25 kg bags",
    category: "HDPE Granules",
  },
  {
    slug: "hdpe-black-uv",
    name: "HDPE Black UV Stabilized",
    description: "UV-stabilized HDPE granules for outdoor applications.",
    image: "/black.jpg",
    minOrderKg: 25,
    specifications: {
      polymer: "HDPE",
      grade: "Extrusion/Injection",
      mfi: "0.8–6 g/10min",
      density: "0.955 g/cm³",
      colorOptions: "Black (carbon black)",
      recycling: "Available",
    },
    applications: ["Pipes", "Outdoor crates", "Automotive parts"],
    packaging: "25 kg bags",
    category: "HDPE Granules",
  },
  {
    slug: "hdpe-recycled-colored",
    name: "HDPE Recycled Colored Granules",
    description: "Recycled HDPE granules in multiple shades for cost-effective products.",
    image: "/8A8CE996-754F-4CC0-A8DA-27E30D69C372.jpeg",
    minOrderKg: 25,
    specifications: {
      polymer: "Reprocessed HDPE",
      grade: "Extrusion/Injection",
      mfi: "Varies by batch",
      density: "0.94–0.96 g/cm³",
      colorOptions: "Mixed shades",
      recycling: "100% recycled",
    },
    applications: ["Bins", "Containers", "Sheets", "Pipes"],
    packaging: "25 kg bags",
    category: "HDPE Granules",
  },
  {
    slug: "hdpe-film-grade",
    name: "HDPE Film Grade Granules",
    description: "HDPE film grade for blown film and packaging industry.",
    image: "/HDPE-Film-grade.jpg",
    minOrderKg: 25,
    specifications: {
      polymer: "HDPE",
      grade: "Film extrusion",
      mfi: "0.1–0.5 g/10min",
      density: "≈0.955 g/cm³",
      colorOptions: "Natural",
      recycling: "Virgin",
    },
    applications: ["Carry bags", "Liners", "Sheets"],
    packaging: "25 kg bags",
    category: "HDPE Granules",
  },
  {
    slug: "hdpe-high-impact",
    name: "HDPE High Impact Granules",
    description: "High-impact resistance HDPE for industrial use.",
    image: "/green.jpg",
    minOrderKg: 25,
    specifications: {
      polymer: "HDPE",
      grade: "Injection",
      mfi: "3–8 g/10min",
      density: "≈0.96 g/cm³",
      colorOptions: "Black / natural",
      recycling: "Virgin & recycled",
    },
    applications: ["Automotive trims", "Industrial products", "Containers"],
    packaging: "25 kg bags",
    category: "HDPE Granules",
  },

  // -------------------- HIPS Granules --------------------
  {
    slug: "hips-natural",
    name: "HIPS Natural Granules",
    description: "High Impact Polystyrene natural granules for packaging and disposables.",
    image: "/natural-white-hips-granules-500x500.webp",
    minOrderKg: 25,
    specifications: {
      polymer: "HIPS",
      grade: "Injection/Extrusion",
      mfi: "2–8 g/10min",
      density: "1.04 g/cm³",
      colorOptions: "Natural",
      recycling: "Virgin & reprocessed",
    },
    applications: ["Disposable cups", "Trays", "Packaging"],
    packaging: "25 kg bags",
    category: "HIPS Granules",
  },
  {
    slug: "hips-black",
    name: "HIPS Black Granules",
    description: "Black colored HIPS with high surface finish for electrical applications.",
    image: "/black-hips-granules.jpeg",
    minOrderKg: 25,
    specifications: {
      polymer: "HIPS",
      grade: "Injection",
      mfi: "3–7 g/10min",
      density: "1.04 g/cm³",
      colorOptions: "Black",
      recycling: "Available",
    },
    applications: ["TV panels", "Electrical housings", "Casings"],
    packaging: "25 kg bags",
    category: "HIPS Granules",
  },
  {
    slug: "hips-colored",
    name: "HIPS Colored Granules",
    description: "Custom-colored HIPS granules for attractive consumer products.",
    image: "/plastic-granules-colours-500x500.webp",
    minOrderKg: 25,
    specifications: {
      polymer: "HIPS",
      grade: "Injection/Extrusion",
      mfi: "Varies",
      density: "1.04 g/cm³",
      colorOptions: "Any color",
      recycling: "Virgin & recycled",
    },
    applications: ["Toys", "Stationery", "Consumer goods"],
    packaging: "25 kg bags",
    category: "HIPS Granules",
  },
  {
    slug: "hips-recycled",
    name: "Recycled HIPS Granules",
    description: "Reprocessed HIPS granules for economical applications.",
    image: "/recycle-hips-granules-500x500.webp",
    minOrderKg: 25,
    specifications: {
      polymer: "Reprocessed HIPS",
      grade: "Injection/Extrusion",
      mfi: "Varies",
      density: "≈1.04 g/cm³",
      colorOptions: "Black / mixed",
      recycling: "100% recycled",
    },
    applications: ["Low-cost items", "Planters", "Utility bins"],
    packaging: "25 kg bags",
    category: "HIPS Granules",
  },
  {
    slug: "hips-food-grade",
    name: "Food Grade HIPS Granules",
    description: "Food-contact safe HIPS for disposable trays and containers.",
    image: "/glass-filled-pbt-500x500.webp",
    minOrderKg: 25,
    specifications: {
      polymer: "Virgin HIPS",
      grade: "Food grade",
      mfi: "2–6 g/10min",
      density: "1.04 g/cm³",
      colorOptions: "Natural / white",
      recycling: "Virgin",
    },
    applications: ["Food trays", "Cups", "Lids"],
    packaging: "25 kg bags",
    category: "HIPS Granules",
  },

  // -------------------- ABS Granules --------------------
  {
    slug: "abs-natural",
    name: "ABS Natural Granules",
    description: "Acrylonitrile Butadiene Styrene (ABS) with balanced toughness and rigidity.",
    image: "/abs-natural-granules-abs-reprocess-granule-injection-molding-new-delhi-delhi-india-931.jpg",
    minOrderKg: 25,
    specifications: {
      polymer: "ABS",
      grade: "Injection",
      mfi: "10–25 g/10min",
      density: "1.05 g/cm³",
      colorOptions: "Natural / white",
      recycling: "Virgin",
    },
    applications: ["Automotive interiors", "Appliances", "Electronics"],
    packaging: "25 kg bags",
    category: "ABS Granules",
  },
  {
    slug: "abs-black",
    name: "ABS Black Granules",
    description: "High-opacity black ABS granules for durable industrial parts.",
    image: "/abs-black-granules-abs-reprocess-granule-mix-scrap-navi-mumbai-maharashtra-india-108.jpg",
    minOrderKg: 25,
    specifications: {
      polymer: "ABS",
      grade: "Injection",
      mfi: "15–25 g/10min",
      density: "1.05 g/cm³",
      colorOptions: "Black",
      recycling: "Available",
    },
    applications: ["Automotive trims", "Electronic housings", "Toys"],
    packaging: "25 kg bags",
    category: "ABS Granules",
  },
  {
    slug: "abs-colored",
    name: "ABS Colored Granules",
    description: "Custom color-matched ABS with gloss finish and impact strength.",
    image: "/abs-colored-plastic-granules.jpg",
    minOrderKg: 25,
    specifications: {
      polymer: "ABS",
      grade: "Injection",
      mfi: "Varies",
      density: "1.05 g/cm³",
      colorOptions: "Any color",
      recycling: "Virgin & recycled",
    },
    applications: ["Consumer goods", "Toys", "Stationery"],
    packaging: "25 kg bags",
    category: "ABS Granules",
  },
  {
    slug: "abs-fire-retardant",
    name: "Fire Retardant ABS",
    description: "ABS granules with flame-retardant additives for electronics and appliances.",
    image: "/abs-flame-retardant-compound-500x500.webp",
    minOrderKg: 25,
    specifications: {
      polymer: "ABS FR",
      grade: "Injection",
      mfi: "10–20 g/10min",
      density: "1.06 g/cm³",
      colorOptions: "Natural / black",
      recycling: "Virgin",
    },
    applications: ["Electrical parts", "TV housings", "Electronics"],
    packaging: "25 kg bags",
    category: "ABS Granules",
  },
  {
    slug: "abs-recycled",
    name: "Recycled ABS Granules",
    description: "Economical recycled ABS granules with decent mechanical strength.",
    image: "/Recycled-ABS-Granules.jpg",
    minOrderKg: 25,
    specifications: {
      polymer: "Reprocessed ABS",
      grade: "Injection",
      mfi: "Varies",
      density: "≈1.05 g/cm³",
      colorOptions: "Black / mixed",
      recycling: "100% recycled",
    },
    applications: ["Non-critical items", "Furniture parts", "Utility goods"],
    packaging: "25 kg bags",
    category: "ABS Granules",
  },

  // -------------------- LDPE Granules --------------------
  {
    slug: "ldpe-natural",
    name: "LDPE Natural Granules",
    description: "Low Density Polyethylene granules with flexibility and clarity.",
    image: "/ldpe-natural-granules.jpg",
    minOrderKg: 25,
    specifications: {
      polymer: "LDPE",
      grade: "Film/Extrusion",
      mfi: "0.2–1.5 g/10min",
      density: "0.92 g/cm³",
      colorOptions: "Natural",
      recycling: "Virgin",
    },
    applications: ["Film wraps", "Carry bags", "Pouches"],
    packaging: "25 kg bags",
    category: "LDPE Granules",
  },
  {
    slug: "ldpe-black",
    name: "LDPE Black Granules",
    description: "Black LDPE granules suitable for film and sheet extrusion.",
    image: "/ldpe-black-granule.jpg",
    minOrderKg: 25,
    specifications: {
      polymer: "LDPE",
      grade: "Extrusion",
      mfi: "0.5–1.2 g/10min",
      density: "0.92 g/cm³",
      colorOptions: "Black",
      recycling: "Virgin & recycled",
    },
    applications: ["Sheets", "Films", "Bags"],
    packaging: "25 kg bags",
    category: "LDPE Granules",
  },
  {
    slug: "ldpe-recycled",
    name: "Recycled LDPE Granules",
    description: "Reprocessed LDPE granules for economical flexible packaging.",
    image: "/recycled-ldpe-granules-500x500.webp",
    minOrderKg: 25,
    specifications: {
      polymer: "Reprocessed LDPE",
      grade: "Extrusion/Film",
      mfi: "Varies",
      density: "≈0.92 g/cm³",
      colorOptions: "Mixed colors",
      recycling: "100% recycled",
    },
    applications: ["Low-cost films", "Sheets", "Linings"],
    packaging: "25 kg bags",
    category: "LDPE Granules",
  },
  {
    slug: "ldpe-colored",
    name: "Colored LDPE Granules",
    description: "Custom shade LDPE granules for flexible packaging solutions.",
    image: "/ldpe-colored-granules-500x500.webp",
    minOrderKg: 25,
    specifications: {
      polymer: "LDPE",
      grade: "Film/Extrusion",
      mfi: "0.3–1.0 g/10min",
      density: "0.92 g/cm³",
      colorOptions: "Any color",
      recycling: "Virgin",
    },
    applications: ["Colored bags", "Packaging films", "Pouches"],
    packaging: "25 kg bags",
    category: "LDPE Granules",
  },
  {
    slug: "ldpe-injection",
    name: "Injection Grade LDPE Granules",
    description: "LDPE injection grade granules with good impact resistance.",
    image: "/lld-injection-grade-500x500.webp",
    minOrderKg: 25,
    specifications: {
      polymer: "LDPE",
      grade: "Injection",
      mfi: "5–20 g/10min",
      density: "0.92 g/cm³",
      colorOptions: "Natural / black",
      recycling: "Virgin",
    },
    applications: ["Caps", "Containers", "Molded products"],
    packaging: "25 kg bags",
    category: "LDPE Granules",
  },

  // -------------------- Blow Grade --------------------
  {
    slug: "blow-hdpe-drum",
    name: "Blow Grade HDPE for Drums",
    description: "Blow grade HDPE granules for large industrial drums and tanks.",
    image: "/hdpe-blue-drum-granules-hdpe-resin-blow-film-grade-ahmedabad-gujarat-india-545.jpg",
    minOrderKg: 25,
    specifications: {
      polymer: "HDPE",
      grade: "Blow molding",
      mfi: "0.3–0.5 g/10min",
      density: "0.955 g/cm³",
      colorOptions: "Natural / black",
      recycling: "Virgin",
    },
    applications: ["Drums", "Tanks", "Canisters"],
    packaging: "25 kg bags",
    category: "Blow Grade",
  },
  {
    slug: "blow-pp-bottle",
    name: "Blow Grade PP for Bottles",
    description: "Polypropylene blow grade for transparent bottles and jars.",
    image: "/colored-polypropylene-granules.png",
    minOrderKg: 25,
    specifications: {
      polymer: "PP",
      grade: "Blow molding",
      mfi: "1–3 g/10min",
      density: "≈0.90 g/cm³",
      colorOptions: "Natural",
      recycling: "Virgin",
    },
    applications: ["Bottles", "Jars", "Containers"],
    packaging: "25 kg bags",
    category: "Blow Grade",
  },
  {
    slug: "blow-ldpe-cans",
    name: "Blow Grade LDPE for Cans",
    description: "LDPE blow molding granules with flexibility and impact strength.",
    image: "/hd-off-grade-granules-500x500.webp",
    minOrderKg: 25,
    specifications: {
      polymer: "LDPE",
      grade: "Blow molding",
      mfi: "0.2–0.6 g/10min",
      density: "0.92 g/cm³",
      colorOptions: "Natural",
      recycling: "Virgin",
    },
    applications: ["Cans", "Small bottles", "Containers"],
    packaging: "25 kg bags",
    category: "Blow Grade",
  },
  {
    slug: "blow-hdpe-milk",
    name: "HDPE Blow Grade Milk Bottles",
    description: "Specialized blow grade HDPE for dairy packaging bottles.",
    image: "/hd-milk-bottles-scrap.jpg",
    minOrderKg: 25,
    specifications: {
      polymer: "HDPE",
      grade: "Blow molding",
      mfi: "0.25–0.5 g/10min",
      density: "0.955 g/cm³",
      colorOptions: "Natural / white",
      recycling: "Virgin",
    },
    applications: ["Milk bottles", "Food packaging"],
    packaging: "25 kg bags",
    category: "Blow Grade",
  },
  {
    slug: "blow-ppcp-jerrycan",
    name: "PPCP Blow Grade Jerry Can Granules",
    description: "Impact-resistant PPCP blow grade for jerry cans.",
    image: "/hdpe-dana-hdpe-prime-virgin-blow-hyderabad-telangana-india-181.jpg",
    minOrderKg: 25,
    specifications: {
      polymer: "PPCP",
      grade: "Blow molding",
      mfi: "1–3 g/10min",
      density: "≈0.91 g/cm³",
      colorOptions: "Natural / blue",
      recycling: "Available",
    },
    applications: ["Jerry cans", "Drums", "Containers"],
    packaging: "25 kg bags",
    category: "Blow Grade",
  },

  // -------------------- Molding Grade --------------------
  {
    slug: "molding-pp-injection",
    name: "Injection Molding PP Granules",
    description: "Virgin PP for injection molding with excellent dimensional stability.",
    image: "/m12rr-hmel-pp-injection-moulding-granules-500x500.webp",
    minOrderKg: 25,
    specifications: {
      polymer: "PP",
      grade: "Injection molding",
      mfi: "10–25 g/10min",
      density: "≈0.90 g/cm³",
      colorOptions: "Natural / colored",
      recycling: "Virgin",
    },
    applications: ["Containers", "Caps", "Household goods"],
    packaging: "25 kg bags",
    category: "Molding Grade",
  },
  {
    slug: "molding-hdpe-injection",
    name: "Injection Molding HDPE Granules",
    description: "HDPE molding grade with toughness and rigidity.",
    image: "/hdpe-injection-molding-grads-500x500.webp",
    minOrderKg: 25,
    specifications: {
      polymer: "HDPE",
      grade: "Injection molding",
      mfi: "5–20 g/10min",
      density: "0.96 g/cm³",
      colorOptions: "Black / natural",
      recycling: "Virgin",
    },
    applications: ["Crates", "Pallets", "Bins"],
    packaging: "25 kg bags",
    category: "Molding Grade",
  },
  {
    slug: "molding-abs",
    name: "ABS Molding Grade Granules",
    description: "Injection grade ABS with high impact strength and gloss.",
    image: "/abs-700-grade-granules-500x500.webp",
    minOrderKg: 25,
    specifications: {
      polymer: "ABS",
      grade: "Injection molding",
      mfi: "15–30 g/10min",
      density: "1.05 g/cm³",
      colorOptions: "Any color",
      recycling: "Available",
    },
    applications: ["Toys", "Electronics", "Automotive interiors"],
    packaging: "25 kg bags",
    category: "Molding Grade",
  },
  {
    slug: "molding-hips",
    name: "HIPS Molding Grade Granules",
    description: "Molding grade HIPS with balanced rigidity and impact.",
    image: "/HIPS-Natural-Granules.jpg",
    minOrderKg: 25,
    specifications: {
      polymer: "HIPS",
      grade: "Injection molding",
      mfi: "4–12 g/10min",
      density: "1.04 g/cm³",
      colorOptions: "Natural / colored",
      recycling: "Available",
    },
    applications: ["Packaging trays", "Cups", "Containers"],
    packaging: "25 kg bags",
    category: "Molding Grade",
  },
  {
    slug: "molding-ldpe",
    name: "LDPE Molding Grade Granules",
    description: "Injection molding LDPE granules for flexible molded products.",
    image: "/White-LDPE-Granules.jpg",
    minOrderKg: 25,
    specifications: {
      polymer: "LDPE",
      grade: "Injection molding",
      mfi: "10–25 g/10min",
      density: "0.92 g/cm³",
      colorOptions: "Natural / black",
      recycling: "Virgin",
    },
    applications: ["Caps", "Flexible components", "Utility goods"],
    packaging: "25 kg bags",
    category: "Molding Grade",
  },
]

export function getProduct(slug: string) {
  return products.find((p) => p.slug === slug)
}

export const productSlugs = products.map((p) => p.slug)
